maintainer       "Sam Lown"
maintainer_email "me@samlown.com"
license          "Apache 2.0"
description      "Installs/Configures planetaki and related services"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.1"
depends          "imagemagick"
depends          "rabbitmq"
depends          "mongodb"
depends          "rails"
depends          "postgresql"
depends          "nginx"
depends          "unicorn"
depends          "god"
